# Site settings
title: Ruka Yoga â€” Yoga Studio
email: rua.hvitulv@icloud.com
description: "Aimed towards a new generation of yoga practitioners who think of yoga critically, not superstitiously, who want to learn to work healthily and integrate balance and sustainability in their lives. A resource for those who want to approach it but also for those who simply want to understand yoga without practicing it. A space for those who have tried and failed to get into it many times before - to try once more."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rukayoga.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
